const data = {
  products: [
    {
      name: "Nike Slim shirt",
      slug: "nike-slim-shirt",
      category: "shirts",
      image: "./images/p1.jpg",
      price: 120,
      countInStock: 10,
      brand: "Nike",
      rating: 4.5,
      numReviews: 10,
      description: "hight quality  shirt ",
    },
    {
      name: "hamadi abid Slim shirt",
      slug: "HA-slim-shirt",
      category: "shirts",
      image: "./images/p1.jpg",
      price: 120,
      countInStock: 10,
      brand: "Nike",
      rating: 4.5,
      numReviews: 10,
      description: "hight quality  shirt ",
    },
    {
      name: "adidas Slim shirt",
      slug: "adidas-slim-shirt",
      category: "shirts",
      image: "./images/p1.jpg",
      price: 120,
      countInStock: 10,
      brand: "Nike",
      rating: 4.5,
      numReviews: 10,
      description: "hight quality  shirt ",
    },
    {
      name: "luke Slim shirt",
      slug: "luke-slim-shirt",
      category: "shirts",
      image: "./images/p1.jpg",
      price: 120,
      countInStock: 10,
      brand: "Nike",
      rating: 4.5,
      numReviews: 10,
      description: "hight quality  shirt ",
    },
  ],
};

export default data;
